import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cn } from '@/lib/utils';
import { Toaster } from '@/components/ui/sonner';
import Footer from '@/components/sections/footer/Footer';
import Header from '@/components/sections/header/Header';
import './globals.css';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Rafay Khan | Portfolio',
  description: 'Generated by create next app',
};

// export const fetchCache = 'force-no-store';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={cn('h-full', 'antialiased', 'font-sans', inter.variable)}>
      <body className='min-h-full flex flex-col'>
        <Header />
        {children}
        <Toaster />
        <Footer />
      </body>
    </html>
  );
}
